---
name: Pre-commit

on:
  - pull_request
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          python3 -m pip install pre-commit
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
      - name: Get some details
        run: |
          which python3
          python3 --version
          python3 -m pip list
      - name: Run pre-commit
        run: pre-commit run --all-files
